---
- name: install pakages
  yum:
    name: " {{ item }}"
    state: present
  loop: "{{ pkgs}}"

- name: create jinja
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: start the service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{pkgs}}"

- name: enable the firewall
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes

  loop: "{{ rule }}"
